#!/usr/bin/env bash

# Backup from history. To be review it

brew tap caskroom/fonts
brew tap caskroom/versions

brew install cmake
brew install diffoscope
brew install docker
brew install gnu-sed
brew install htop
brew install httpie
brew install mtr
brew install neovim
brew install nginx
brew install nmap
brew install openconnect
brew install pgcli
brew install postgresql
brew install tmux
brew install tree
brew install unp
brew install yarn --without-node
brew install youtube-dl
brew install zsh

brew cask install amethyst
brew cask install docker
brew cask install firefox-developer-edition
brew cask install font-fira-code
brew cask install font-hack
brew cask install hipchat
brew cask install iterm2
brew cask install java
brew cask install java8
brew cask install licecap
brew cask install postman
brew cask install recordit
brew cask install skype
brew cask install spotify
brew cask install squidman
brew cask install telegram-desktop
brew cask install visual-studio-code

nvm install --lts

pip install --upgrade pip
pip install neovim
