[character]
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"
vicmd_symbol = "[←](bold green)"

[aws]
disabled = true

[line_break]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true
